server {
    listen       80;
    server_name  localhost;

    # 1. 前端页面
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. 代理到后端的 7001 端口
    location /api/ {
        # 因为是分开部署，直接用你服务器的公网 IP 
        # （或者 Linux 默认的宿主机 Docker IP: 172.17.0.1）
        proxy_pass http://1.14.162.29:7001/; 
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}